#!/usr/bin/env bash
# Usage: ./1-world_wide_web <domain> <subdomain>
# Configure domain zone so subdomain www points to load-balancer IP (lb-01)

domain_info () {
  if [ -n "$2" ]
  then
    dig "$2.$1" | grep -A1 'ANSWER SECTION:' | paste - - | awk -v \
	subdomain="$2" '{print "The subdomain " subdomain " is a " $7 " record and\
 points to " $8}'
  else
	  dig "www.$1" | grep -A1 'ANSWER SECTION:' | paste - - | awk '{print "The\
 domain www is a " $7 " record and points to " $8}'
	  dig "lb-01.$1" | grep -A1 'ANSWER SECTION:' | paste - - | awk '{print "The\
 domain lb-01 is a " $7 " record and points to " $8}'
	  dig "web-01.$1" | grep -A1 'ANSWER SECTION:' | paste - - | awk '{print "The\
 domain web-01 is a " $7 " record and points to " $8}'
	  dig "web-02.$1" | grep -A1 'ANSWER SECTION:' | paste - - | awk '{print "The\
 domain web-02 is a " $7 " record and points to " $8}'
  fi
}

domain_info "$1" "$2"
