#!/usr/bin/env bash
#Configure domain so subdomain www points to load-balancer IP (lb-01)
#Add the subdomain www to your domain, point it to your lb-01 IP
#Add the subdomain lb-01 to your domain, point it to your lb-01 IP
#Add the subdomain web-01 to your domain, point it to your web-01 IP
#Add the subdomain web-02 to your domain, point it to your web-02 IP

subdomains_all=( "www" "lb-01" "web-01" "web-02" )

runDig () {
    subdomain=$1
    domain=$2

    dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -1 | awk -v s="$subdomain" 'BEGIN { FS = " " } ; { print "The subdomain " s " is a " $4 " record and points to " $5 }'
}

if [ $# -eq 1 ]; then
    domain="$1"
    for i in "${subdomains_all[@]}"
    do
	runDig "$i" "$domain"
    done
elif [ $# -eq 2 ]; then
    domain="$1"
    subdomain="$2"
    runDig "$subdomain" "$domain"
fi
