#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Hello World" when queried
#++    at the root with a curl GET request.

# Update package lists
sudo apt update

# Install Nginx
sudo apt install nginx -y

# Create a new default file for the web server
sudo touch /var/www/html/index.html

# Add content to the index.html file
echo "Hello World!" | sudo tee /var/www/html/index.html

# Adjust firewall rules to allow traffic on port 80 (assuming UFW firewall)
sudo ufw allow 80

# Restart Nginx (avoiding systemctl)
sudo service nginx restart

# Verify Nginx is running
sudo service nginx status

# Show IP address (optional)
# hostname -I | awk '{print $1}'
