#!/usr/bin/env bash
#The name of the custom HTTP header must be X-Served-By
#The value of the custom HTTP header must be the hostname of the server Nginx is running on
#Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
#configure web-02 to be identical to web-01

sudo apt-get -y update
sudo apt-get -y install nginx

sudo mkdir -p /var/www/html
touch /var/www/html/index.html
touch /var/www/html/404.html
echo 'Hello World!' > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /var/www/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 http://cuberule.com/;
    }

    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
