#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server
#Configure HAproxy so that it send traffic to web-01 and web-02
#Explain the request in roundrobin algorithm
#Make sure that HAproxy can be managed via an init script

# Install HAProxy 1.8 with required dependencies
apt-get update
apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get install -y haproxy=1.8.*

# Enable HAProxy management via init script
echo "ENABLED=1" >> /etc/default/haproxy

# Create a new HAProxy configuration file
# Move existing config (if any)
mv /etc/haproxy/haproxy.cfg{.original,}
touch /etc/haproxy/haproxy.cfg

# HAProxy configuration
cat << EOF >> /etc/haproxy/haproxy.cfg
global
  log 127.0.0.1 local0 notice
  maxconn 2000
  user haproxy
  group haproxy

defaults
  log global
  mode http
  option httplog
  option dontlognull
  retries 3
  option redispatch
  timeout connect 5000
  timeout client 10000
  timeout server 10000

listen hbnb
  bind 0.0.0.0:80
  mode http
  stats enable
  stats uri /haproxy?stats
  balance roundrobin
  option httpclose
  option forwardfor
  server 528720-web-01 3.86.7.100:80 check
  server 528720-web-02 100.26.212.112:80 check
EOF

# Start the HAProxy service
service haproxy start

echo "HAProxy 1.8 is installed and configured!"
