#!/usr/bin/env bash
# Displays "Best School" 10 times using a while loop.
#   On the 9th iteration, displays "Hi" before "Best School".

rep=0

while [ $rep -lt 10 ]
do
  if [ $rep -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( rep++ ))
done
